paths:
  # Root of all neural HDF5 data (this is what your BrainDataset / build_datasets expects)
  data_dir: "data/01_raw/brain-to-text-25/t15_copyTask_neuralData/hdf5_data_final"

  # Pretrained baseline (if/when you use it)
  baseline_root: "data/01_raw/brain-to-text-25/t15_pretrained_rnn_baseline/t15_pretrained_rnn_baseline"
  baseline_args_yaml:      "${paths.baseline_root}/args.yaml"
  baseline_checkpoint_dir: "${paths.baseline_root}/checkpoint"
  baseline_best_checkpoint: "${paths.baseline_root}/best_checkpoint"
  baseline_training_log:   "${paths.baseline_root}/training_log"

loader:
  batch_size: 32
  num_workers: 0
  pin_memory: false
  shuffle_train: true


# model / training
train:
  device: "cuda"            # "cuda" or "cpu"
  epochs: 5
  lr: 0.001
  blank_id: 0
  vocab: [
    'AA','AE','AH','AO','AW','AY','B','CH','D','DH','EH','ER','EY','F','G','HH',
    'IH','IY','JH','K','L','M','N','NG','OW','OY','P','R','S','SH','T','TH','UH','UW','V','W','Y','Z','|'
  ]
  data_input_size: 512
  adapter_output_size: 256
  hidden_size: 512
  num_layers: 1
  bidirectional: false
  n_head: 8                 # transformer
  dim_feedforward: 512
  use_checkpoint_variants:  # (model, use_checkpoint) pairs
    - ["RNN", true]
    - ["RNN", false]
    - ["LSTM", true]
    - ["LSTM", false]
    - ["GRU", true]
    - ["GRU", false]
    - ["TRANSFORMER", true]
    - ["TRANSFORMER", false]
